insert into genres (genre_name) values ('Rock');
insert into genres (genre_name) values ('Rap');
insert into genres (genre_name) values ('Classic');
insert into genres (genre_name) values ('Dance');
insert into genres (genre_name) values ('Pop');
insert into singers (singer_name) values ('Boney M.');
insert into singers (singer_name) values ('Papa Roach');
insert into singers (singer_name) values ('Billie Eilish');
insert into singers (singer_name) values ('Noize MC');
insert into singers (singer_name) values ('Olga Buzova');
insert into singers (singer_name) values ('Gorrillaz');
insert into singers (singer_name) values ('Beethoven');
insert into singers (singer_name) values ('Mozart');
insert into singers (singer_name) values ('Ленинград');
insert into singers (singer_name) values ('The Hatters');
insert into singers (singer_name) values ('Little Big');
insert into singers (singer_name) values ('Face');
insert into singers (singer_name) values ('Morgenstren');
insert into singers (singer_name) values ('Wagner');
insert into singers (singer_name) values ('System of A Down');
insert into singers (singer_name) values ('Джарахов');
insert into singers (singer_name) values ('Klaas');
insert into singers (singer_name) values ('PIZZA');
insert into albums (title, year) values ('Легкий способ бросить любить', 2022);
insert into albums (title, year) values ('GO BANANAS', 2015);
insert into albums (title, year) values ('Requiem in D Minor', 1968);
insert into albums (title, year) values ('Forte & Piano', 2012);
insert into albums (title, year) values ('Улыбка', 2019);
insert into albums (title, year) values ('Filling Our Lives', 2005);
insert into albums (title, year) values ('MILLION DOLLAR: HAPPINESS', 2021);
insert into albums (title, year) values ('Всякое', 1990);
insert into albums (title, year) values ('Song Machine, Season One: Strange Timez', 2001);
insert into albums (title, year) values ('Who Do You Trust?', 2007);
insert into albums (title, year) values ('Новый альбом', 2015);
insert into albums (title, year) values ('Happier Than Ever', 2020);
insert into tracks (track_name, duration, albumid) values ('Неразбериха', 3, 11);
insert into tracks (track_name, duration, albumid) values ('GO BANANAS', 3, 2);
insert into tracks (track_name, duration, albumid) values ('Masterpieces: Lacrimosa', 4, 3);
insert into tracks (track_name, duration, albumid) values ('Вокзал', 5, 1);
insert into tracks (track_name, duration, albumid) values ('Bad guy', 3, 10);
insert into tracks (track_name, duration, albumid) values ('Просто друг', 2, 1);
insert into tracks (track_name, duration, albumid) values ('Forte&Piano', 3, 4);
insert into tracks (track_name, duration, albumid) values ('Cool song', 4, 6);
insert into tracks (track_name, duration, albumid) values ('Пыль', 2, 7);
insert into tracks (track_name, duration, albumid) values ('Вояж', 3, 8);
insert into tracks (track_name, duration, albumid) values ('Жадина', 4, 11);
insert into tracks (track_name, duration, albumid) values ('Fall in love', 5, 12);
insert into tracks (track_name, duration, albumid) values ('Requiem', 14, 3);
insert into tracks (track_name, duration, albumid) values ('Лифт', 2, 5);
insert into tracks (track_name, duration, albumid) values ('SOS', 5, 6);
insert into tracks (track_name, duration, albumid) values ('Чушь', 5, 7);
insert into tracks (track_name, duration, albumid) values ('Выборы', 4, 8);
insert into tracks (track_name, duration, albumid) values ('Feel good', 7, 9);
insert into tracks (track_name, duration, albumid) values ('Why?', 4, 10);
insert into tracks (track_name, duration, albumid) values ('Future', 3, 11);
insert into tracks (track_name, duration, albumid) values ('Мой мир', 4, 5);
insert into tracks (track_name, duration, albumid) values ('Ты мой хороший', 2, 6);
insert into tracks (track_name, duration, albumid) values ('It is my life', 3.8, 3);
insert into tracks (track_name, duration, albumid) values ('After life', 38, 8);
insert into tracks (track_name, duration, albumid) values ('Riddle', 1.8, 3);
insert into collections (col_name, year) values ('Антология золотых хитов', 2022);
insert into collections (col_name, year) values ('Классика', 2015);
insert into collections (col_name, year) values ('Хиты-незабудки', 2000);
insert into collections (col_name, year) values ('Кто это слушает?', 2017);
insert into collections (col_name, year) values ('Тренировка', 2008);
insert into collections (col_name, year) values ('Для учёбы', 2015);
insert into collections (col_name, year) values ('Для работы', 2020);
insert into collections (col_name, year) values ('Молодёжно', 1990);
insert into collections (col_name, year) values ('Летняя', 2011);
insert into collections (col_name, year) values ('Популярная', 2017);
insert into collections (col_name, year) values ('Вечные хиты', 2019);
insert into collections (col_name, year) values ('Расслабиться', 2020);
insert into singersgenres (singerid, genreid) values (1, 5);
insert into singersgenres (singerid, genreid) values (2, 1);
insert into singersgenres (singerid, genreid) values (3, 4);
insert into singersgenres (singerid, genreid) values (3, 2);
insert into singersgenres (singerid, genreid) values (4, 1);
insert into singersgenres (singerid, genreid) values (4, 2);
insert into singersgenres (singerid, genreid) values (4, 4);
insert into singersgenres (singerid, genreid) values (5, 5);
insert into singersgenres (singerid, genreid) values (6, 4);
insert into singersgenres (singerid, genreid) values (6, 5);
insert into singersgenres (singerid, genreid) values (7, 3);
insert into singersgenres (singerid, genreid) values (8, 3);
insert into singersgenres (singerid, genreid) values (9, 5);
insert into singersgenres (singerid, genreid) values (10, 1);
insert into singersgenres (singerid, genreid) values (10, 2);
insert into singersgenres (singerid, genreid) values (10, 5);
insert into singersgenres (singerid, genreid) values (10, 1);
insert into singersgenres (singerid, genreid) values (11, 2);
insert into singersgenres (singerid, genreid) values (11, 4);
insert into singersgenres (singerid, genreid) values (11, 5);
insert into singersgenres (singerid, genreid) values (12, 2);
insert into singersgenres (singerid, genreid) values (13, 2);
insert into singersgenres (singerid, genreid) values (13, 3);
insert into singersgenres (singerid, genreid) values (14, 1);
insert into singersgenres (singerid, genreid) values (14, 5);
insert into singersgenres (singerid, genreid) values (15, 2);
insert into singersgenres (singerid, genreid) values (15, 4);
insert into singersgenres (singerid, genreid) values (15, 5);
insert into singersgenres (singerid, genreid) values (16, 5);
insert into singersgenres (singerid, genreid) values (17, 4);
insert into singersgenres (singerid, genreid) values (18, 5);
insert into singersalbums (singerid, albumid) values (1, 6);
insert into singersalbums (singerid, albumid) values (2, 10);
insert into singersalbums (singerid, albumid) values (3, 12);
insert into singersalbums (singerid, albumid) values (4, 11);
insert into singersalbums (singerid, albumid) values (4, 8);
insert into singersalbums (singerid, albumid) values (4, 1);
insert into singersalbums (singerid, albumid) values (5, 7);
insert into singersalbums (singerid, albumid) values (6, 9);
insert into singersalbums (singerid, albumid) values (6, 11);
insert into singersalbums (singerid, albumid) values (7, 3);
insert into singersalbums (singerid, albumid) values (8, 3);
insert into singersalbums (singerid, albumid) values (9, 8);
insert into singersalbums (singerid, albumid) values (9, 7);
insert into singersalbums (singerid, albumid) values (10, 4);
insert into singersalbums (singerid, albumid) values (10, 1);
insert into singersalbums (singerid, albumid) values (10, 2);
insert into singersalbums (singerid, albumid) values (11, 2);
insert into singersalbums (singerid, albumid) values (11, 1);
insert into singersalbums (singerid, albumid) values (12, 7);
insert into singersalbums (singerid, albumid) values (13, 7);
insert into singersalbums (singerid, albumid) values (14, 9);
insert into singersalbums (singerid, albumid) values (15, 6);
insert into singersalbums (singerid, albumid) values (16, 1);
insert into singersalbums (singerid, albumid) values (16, 4);
insert into singersalbums (singerid, albumid) values (17, 12);
insert into singersalbums (singerid, albumid) values (18, 5);
insert into singersalbums (singerid, albumid) values (18, 1);
insert into collectionstracks (collectionid, trackid) values (1, 1);
insert into collectionstracks (collectionid, trackid) values (1, 3);
insert into collectionstracks (collectionid, trackid) values (1, 2);
insert into collectionstracks (collectionid, trackid) values (1, 4);
insert into collectionstracks (collectionid, trackid) values (2, 12);
insert into collectionstracks (collectionid, trackid) values (2, 2);
insert into collectionstracks (collectionid, trackid) values (2, 3);
insert into collectionstracks (collectionid, trackid) values (2, 5);
insert into collectionstracks (collectionid, trackid) values (2, 6);
insert into collectionstracks (collectionid, trackid) values (2, 7);
insert into collectionstracks (collectionid, trackid) values (3, 3);
insert into collectionstracks (collectionid, trackid) values (3, 7);
insert into collectionstracks (collectionid, trackid) values (3, 8);
insert into collectionstracks (collectionid, trackid) values (3, 10);
insert into collectionstracks (collectionid, trackid) values (3, 11);
insert into collectionstracks (collectionid, trackid) values (3, 12);
insert into collectionstracks (collectionid, trackid) values (3, 13);
insert into collectionstracks (collectionid, trackid) values (3, 14);
insert into collectionstracks (collectionid, trackid) values (3, 15);
insert into collectionstracks (collectionid, trackid) values (3, 16);
insert into collectionstracks (collectionid, trackid) values (3, 17);
insert into collectionstracks (collectionid, trackid) values (4, 9);
insert into collectionstracks (collectionid, trackid) values (5, 1);
insert into collectionstracks (collectionid, trackid) values (5, 2);
insert into collectionstracks (collectionid, trackid) values (5, 3);
insert into collectionstracks (collectionid, trackid) values (5, 4);
insert into collectionstracks (collectionid, trackid) values (5, 5);
insert into collectionstracks (collectionid, trackid) values (5, 6);
insert into collectionstracks (collectionid, trackid) values (6, 6);
insert into collectionstracks (collectionid, trackid) values (6, 7);
insert into collectionstracks (collectionid, trackid) values (6, 8);
insert into collectionstracks (collectionid, trackid) values (6, 10);
insert into collectionstracks (collectionid, trackid) values (7, 11);
insert into collectionstracks (collectionid, trackid) values (7, 12);
insert into collectionstracks (collectionid, trackid) values (8, 13);
insert into collectionstracks (collectionid, trackid) values (8, 14);
insert into collectionstracks (collectionid, trackid) values (8, 15);
insert into collectionstracks (collectionid, trackid) values (8, 16);
insert into collectionstracks (collectionid, trackid) values (9, 17);
insert into collectionstracks (collectionid, trackid) values (9, 18);
insert into collectionstracks (collectionid, trackid) values (9, 19);
insert into collectionstracks (collectionid, trackid) values (9, 20);
insert into collectionstracks (collectionid, trackid) values (9, 1);
insert into collectionstracks (collectionid, trackid) values (9, 2);
insert into collectionstracks (collectionid, trackid) values (9, 4);
insert into collectionstracks (collectionid, trackid) values (9, 6);
insert into collectionstracks (collectionid, trackid) values (10, 11);
insert into collectionstracks (collectionid, trackid) values (10, 12);
insert into collectionstracks (collectionid, trackid) values (10, 15);
insert into collectionstracks (collectionid, trackid) values (10, 16);
insert into collectionstracks (collectionid, trackid) values (10, 17);
insert into collectionstracks (collectionid, trackid) values (11, 19);
insert into collectionstracks (collectionid, trackid) values (11, 20);
insert into collectionstracks (collectionid, trackid) values (11, 1);
insert into collectionstracks (collectionid, trackid) values (12, 3);
insert into collectionstracks (collectionid, trackid) values (12, 4);
insert into collectionstracks (collectionid, trackid) values (12, 5);
insert into collectionstracks (collectionid, trackid) values (12, 6);
insert into collectionstracks (collectionid, trackid) values (12, 7);
insert into collectionstracks (collectionid, trackid) values (12, 8);
insert into collectionstracks (collectionid, trackid) values (12, 2);
insert into collectionstracks (collectionid, trackid) values (12, 19);
insert into collectionstracks (collectionid, trackid) values (12, 20);
insert into collectionstracks (collectionid, trackid) values (12, 12);